apiVersion: v1
apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  selector:
    run: mysql
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    matchLabels:
      run: mysql
  replicas: 1
  template:
    metadata:
      labels:
        run: mysql
    spec:
      restartPolicy: Always
      containers:
      - name: mysql
        imagePullPolicy: Never
        image: my-mysql
        ports:
        - name: sql
          containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim