apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    run: ftps
spec:
  type: LoadBalancer
  ports:
  - port: 21
    name: ftps
  selector:
    run: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      run: ftps
  replicas: 1
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - name: ftps
        image: my-ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21